version: "3.8"

services:
  testproxy:
    image: nginx:1.21-alpine
    depends_on:
      - "ticketclient"
    volumes:
      - ./TicketProxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "7000:80"

  testclient:
    container_name: ticket-client
    build:
      context: ./TicketClient
      target: development-stage
    command: npm run docker-start
    volumes:
      - ./TicketClient:/app
      - /app/node_modules
    restart: always
    expose:
      - "80"

  ticketsender:
    container_name: ticket-sender
    build:
      context: ./TicketSender
      target: development
    command: npm run docker-start
    volumes:
      - ./TicketSender:/app
      - /app/node_modules
    restart: always
    depends_on:
      - "rabbitmq"

  ticketdb: # login SA:49R8MXw#49c6wT9Q8!
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "49R8MXw#49c6wT9Q8!"
      MSSQL_PID: "Express"
    restart: always
    ports:
      - "1433:1433"

  rabbitmq: # login guest:guest
    image: rabbitmq:3-management
    hostname: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
